"""Full course catalog seed data — see database.py seed_courses(). Regenerate
from the master xlsx if the catalog changes; this file is intentionally just
data, no logic."""

# v5 (Aug 2026) — error-proofing pass: verified syntax, tuple shapes, no
# duplicate/near-duplicate names, cleaned stray whitespace/double-spaces,
# fixed 3 mangled faculty names (SARTHI IAS -> Sarrthi IAS, LEVEL UP IAS ->
# Levelup IAS), confirmed all prices numeric & all section keys well-formed.
# One unresolved data ambiguity flagged separately for Professor to confirm:
# two "Lukmaan IAS ... Ansari Sir" rows share the same name but differ in
# price/section — kept both since they may be genuinely different offerings.
COURSE_SEED = [
    # (name, faculty, medium, notes, price, [section_keys])
    ('KGS – Complete BPSC Foundation (Bilingual/Hinglish, NEW)', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['bpsc']),
    ('StudyIQ – Agriculture', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_agriculture']),
    ('2026 | 2025 both — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_anthropology']),
    ('2026 — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology']),
    ('2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology']),
    ('Anthropology Advance 2025 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology']),
    ('Anthropology Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_anthropology']),
    ('Anthropology QEP+ 2026', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_anthropology']),
    ('Anthropology — Karandeep Sir 2026', 'Levelup IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology']),
    ('CP Kaushik Sir 2027 (ex-Drishti faculty)', 'CP Kaushik Sir', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology']),
    ('DAMP 2025 Levelup IAS', 'Levelup IAS', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['optional_anthropology']),
    ('Harpreet Kukreja 2026 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology']),
    ('Hima Bindu 2025', 'Hima Bindu', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_anthropology']),
    ('Natraj Sir 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_anthropology']),
    ('Natraj Sir — Anthropology QEP 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_anthropology']),
    ('PW – Anthropology Optional', 'PW', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_anthropology']),
    ('Shiva Teja — Anthropology Advance 555 — Ace With Ease', 'Ace With Ease', 'Both', 'Complete course with handouts, lifetime access', 900.0, ['optional_anthropology']),
    ('Sumit Rewri 2027 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_anthropology']),
    ('Ranker Classes • Study IQ • PW Only IAS', 'Ranker Classes', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_commerce_and_accountancy']),
    ('Bliss Point 2026', 'Bliss Point', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_economics']),
    ('De Facto — 2026 — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_economics']),
    ('PCB 15/16 – Mrunal Sir (Economics)', 'Mrunal', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Rishi Jain – Economics (Hindi)', 'Economics (Hindi)', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['optional_economics', 'upsc_subject_specific']),
    ('Shivin Chaudhary – Economics', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_subject_specific']),
    ('Vibhash Jha 2026 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_economics']),
    ('Sunya IAS • Hornbill • Vajiram & Ravi', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_forestry']),
    ('Crash Course — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography']),
    ('Geography Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_geography']),
    ('Geography QEP+ 2026', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography']),
    ('Geography QEP+ 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_geography']),
    ('Himanshu Sir — Geography 500+', 'Geography 500+', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography']),
    ('Himanshu Sir — Guidance IAS x Sarrthi', 'Guidance IAS x Sarrthi', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_geography']),
    ('Himanshu Thapa — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography']),
    ('StudyIQ – Geography Optional', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_geography']),
    ('Vikas Divyakirti Sir • PW Only IAS • Study IQ • KGS', 'PW Only IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_hindi_literature']),
    ('Awadh Ojha Sir (English)', 'Awadh Ojha Sir', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history']),
    ('History Optional 2027 | Sarrthi IAS | Piyush Sir', 'Sarrthi IAS / Piyush Sir', 'Both', 'Complete History Optional batch for CSE 2027', 700.0, ['optional_history']),
    ('History Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history']),
    ('History Optional Crash Course — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_history']),
    ('History Optional – PYQ Course', 'PYQ Course', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_history']),
    ('History QEP cum Crash Course — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_history']),
    ('HISTORY 2027/26', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_history']),
    ('Kirthika Mam – Unacademy', 'Unacademy', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history']),
    ('PW – Ahlawat Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_history']),
    ('KGS – Mathematics Optional (Bilingual, NEW)', 'KGS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_mathematics']),
    ('Mathocrate — Math Optional • PW — Math Crash Course', 'Mathocrate', 'Both', 'Crash batch', 800.0, ['optional_mathematics']),
    ('Next IAS • PW • Mathocrate • Study IQ • KGS', 'Next IAS', 'Both', 'Main batch', 800.0, ['optional_mathematics']),
    ('Mitra IAS • Tanu Jain • Study IQ • PW • KGS', 'Mitra IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_philosophy']),
    ('Philosophy Optional Classroom Programme 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_philosophy']),
    ('Philosophy QEP Mains 2026/2027 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Crash batch', 400.0, ['optional_philosophy']),
    ('Physics Optional Classroom Programme 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_physics']),
    ('2026 / 2024 — Vision IAS / Vajiram & Ravi', 'Vision IAS / Vajiram & Ravi', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psir']),
    ('Bhartendu Sir 2026 — PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('Next IAS 2025', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_psir']),
    ('PSIR QEP — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_psir']),
    ('PSIR — OGP 2026', 'OGP 2026', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psir']),
    ('PW – Adarsh Sir', 'PW', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('PW – Eng Bharat Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('Piyush Chaubey Sir 2026|2025 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('Rahul Puri 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_psir']),
    ('Rajesh Mishra', 'Rajesh Mishra', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('Shashank Tyagi — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_psir']),
    ('Raus x Anantam IAS • Study IQ', 'Raus x Anantam IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_psychology']),
    ('Lukmaan IAS — Ansari Sir', 'Ansari Sir', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_public_administration']),
    ('PW / Study IQ / KGS — 2026 batches', '2026 batches', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_public_administration']),
    ('Public Administration Optional Classroom Programme 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['optional_public_administration']),
    ('Sarrthi IAS — Ashutosh Pandey', 'Ashutosh Pandey', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_public_administration']),
    ('Sarrthi IAS — Pub Ad QEP', 'Pub Ad QEP', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_public_administration']),
    ('2026 + S Pandey 2025 — PW / Study IQ / KGS', 'PW / Study IQ / KGS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology']),
    ('2026 — Sleepy Classes', 'Sleepy Classes', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology']),
    ('Crash Course + Answer Writing Program — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology']),
    ('Diwakar Bothra 2026|2027 both — Study IQ', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology']),
    ('Nishant Sir 2023', 'Nishant Sir', 'Both', 'Complete course with handouts, lifetime access', 450.0, ['optional_sociology']),
    ('Nishant Sir — Sociology Crash Course 2025', 'Nishant Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology']),
    ('PW – Sociology (Hindi)', 'PW', 'Hindi', 'Complete course with handouts, lifetime access', 800.0, ['optional_sociology']),
    ('Pranay Agrawal 2025|2026|2027 all — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology']),
    ('Pranay Agrawal Sir — Sociology QEP 2026 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology']),
    ('Raj Sir 2026 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology']),
    ('Sarrthi IAS Optional 2027 (Sociology/Anthropology/PSIR)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology', 'optional_anthropology', 'optional_psir']),
    ("Smriti Ma'am 2026 — Vision IAS", 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['optional_sociology']),
    ('Sociology Crash Course 2025 — Understand UPSC', 'Understand UPSC', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['optional_sociology']),
    ('Sociology — Sleepy Classes Batch 4 2026', 'Sleepy Classes', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['optional_sociology']),
    ('Triumph IAS – Sociology', 'Triumph IAS', 'Both', 'Complete course with handouts, lifetime access', 100.0, ['optional_sociology']),
    ('Vikas Ranjan 2026', 'Vikas Ranjan', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['optional_sociology']),
    ('StudyIQ UPSC + UKPSC', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['ukpsc']),
    ('Study IQ 2026', 'Study IQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['uppsc']),
    ('UPPSC Samagra Batch (Forum IAS)', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['uppsc']),
    ('UPPSC Sarv Saksham Foundation 2026', 'PW', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['uppsc']),
    ('CA Mains 2026 + 2027 Live — Satvik Bhan', 'Satvik Bhan', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca']),
    ('CA Mains 2026/27 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ca']),
    ('CA VA Mains 2026 + CA VA Live 2027 both — Dipin Sir', 'Dipin Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ca']),
    ('Dipin Sir CA-VA (Mains & Prelims)', 'Dipin Sir', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca']),
    ('Mudit Jain Yearlong CA 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ca']),
    ('Mudit Jain – Current Affairs 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ca']),
    ('Amit Garg CSAT 2027', 'Amit Garg', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT 2026 — Hope Tushant', 'Hope Tushant', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT 2026 — Sudarshan Lodha', 'Sudarshan Lodha', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT 2027 — Amit Garg', 'Amit Garg', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT Hindi 2026 — Madhukar Kotwe', 'Madhukar Kotwe', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT by IITians 2027 — Sunya IAS', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT – Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT – Sunya IAS', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('CSAT — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Careerwill – CSAT', 'Careerwill', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('PW Only IAS 2027 — Rishabh Sharma', 'Rishabh Sharma', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('PW – Rishab Sir', 'PW', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Ram Mohan Pandey – Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Sarrthi IAS CSAT 2027', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Sunya IAS – CSAT', 'Sunya IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('UNGIST x Sarrthi 2026 — Ram Mohan Pandey Sir', 'Ram Mohan Pandey Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Vision IAS – English (With Notes)', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Vision IAS – Hindi (Without Notes)', 'Vision IAS', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_csat']),
    ('Essay (Mudit Jain) 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_essay']),
    ('Forum-IAS Essay Guidance Programme 2026', 'Forum IAS', 'Both', 'Specialized Essay paper guidance, brainstorming & writing practice for Mains 2026', 250.0, ['upsc_essay']),
    ('Shubhra Ranjan – Essay 2026', 'Essay 2026', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_essay']),
    ('Ethics (Mudit Jain) 2027', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ethics']),
    ('Ethics Marks Booster 2026', 'Mudit Jain Sir', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ethics']),
    ('Ethics Samagra (Hindi Medium) — Piyush Sir', 'Piyush Sir', 'Hindi', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ethics']),
    ('Ethics by Piyush Sir 2027', 'Piyush Sir', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_ethics']),
    ('Lukmaan IAS – Ansari Sir', 'Lukmaan IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_ethics']),
    ('Buniyaad – PW', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation']),
    ('Forum IAS — GS 2027', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 1200.0, ['upsc_foundation']),
    ('Foundation Course 2026/27 — Next IAS', 'Next IAS', 'Both', 'Complete course with handouts, lifetime access', 1500.0, ['upsc_foundation']),
    ('GS Foundation 2027/28 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation']),
    ('GS Foundation Batch (1/3/4/5/6 — any one)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 600.0, ['upsc_foundation']),
    ('Khan Sir – UPSC Foundation', 'Khan Sir', 'Hindi', 'Complete course with handouts, lifetime access', 850.0, ['upsc_foundation']),
    ('Live/Recorded Foundation 2027/28 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_foundation']),
    ('MagnaCarta Foundation 5 (2027)', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_foundation']),
    ('Physics Wallah – GS Foundation (Hindi + English)', 'Physics Wallah', 'English', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation']),
    ('Smart Foundation Batch 2027/28/29 — PW OnlyIAS', 'PW OnlyIAS', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['upsc_foundation']),
    ('Smart Foundation Batch 2027/28/29 — StudyIQ', 'StudyIQ', 'Both', 'Complete course with handouts, lifetime access', 700.0, ['upsc_foundation']),
    ('Unacademy – GS Foundation', 'Unacademy', 'English', 'Complete course with handouts, lifetime access', 800.0, ['upsc_foundation']),
    ('AWFG 2026', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Conquer Mains 2026 (Satyam Jain) — Understand UPSC', 'Understand UPSC', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Decode Mains 2026/27 (Mudit Jain) — Combo without CA', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains']),
    ('Decode Mains PRO 2027 — Mudit Jain', 'Mudit Jain', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Forum IAS MGP 2027', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains']),
    ('Forum-IAS GSAP+ PYQ Anchored Classes For Mains 2026', 'Forum IAS', 'Both', 'GS Augmentation Programme Plus — PYQ-anchored Mains 2026 syllabus coverage & practice', 350.0, ['upsc_mains', 'upsc_pyq']),
    ('LevelUP MMP 2026', 'LevelUp', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains']),
    ('M.K. Yadav – QEP 2026', 'M.K. Yadav', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('MK Yadav QEP & TEP 2026/27', 'MK Yadav', 'Both', 'Complete course with handouts, lifetime access', 450.0, ['upsc_mains']),
    ('MMP+ 2026 (Sarrthi IAS)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_mains']),
    ('MMP+ 2027 (Sarrthi IAS)', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains']),
    ('Mains Edge Vision IAS 2026', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Mains Excellence Plus — Combo with CA', 'Combo with CA', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains']),
    ('Mains QEP 8 — Mrunal Sir', 'Mrunal Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_mains']),
    ('Nitya Pargati 2027 Batch 3', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Sankalp Mains — Sudarshan Lodha', 'Sudarshan Lodha', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Shabbir Sir – Essay', 'Essay', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Smash Mains 2026', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_mains']),
    ('Think IAS by Prakash Chitkara (Mains Module)', 'Prakash Chitkara', 'Both', 'Complete course with handouts, lifetime access', 500.0, ['upsc_mains']),
    ('Vajiram Sure Shot Mains 2027', 'Vajiram & Ravi', 'Both', 'Dedicated Mains 2027 mentorship & answer writing program', 400.0, ['upsc_mains']),
    ('Write Smart (Shivin Chaudhary)', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_mains']),
    ('Write Smart + GS-3 Module — Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_mains']),
    ('Dominate Prelims 2026 — Civilsdaily', 'Civilsdaily', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_prelims']),
    ('Fast Track Course 2026 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims']),
    ('Navigator 2026 Batch 1 & 3 — Sarrthi IAS', 'Sarrthi IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims']),
    ('PMP (Prelims Master Program) — LevelUp IAS', 'LevelUp IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_prelims']),
    ('PRRC + SFG (The Discipline Builder) — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims']),
    ('Prelims Crash Batch — PW OnlyIAS / Target UPSC', 'PW OnlyIAS / Target UPSC', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_prelims']),
    ('Vajiram Power Up Prelims Combo 2027 (GS+CA)', 'Vajiram & Ravi', 'Both', 'Combo batch covering Prelims GS + Current Affairs together', 350.0, ['upsc_prelims', 'upsc_ca']),
    ('Logical Elimination 2026 — Civil Daily IAS', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_pyq']),
    ('PYQ 2026 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq']),
    ('PYQ Edge, UPSC Compass 2026 — Saurabh Arbole Sir', 'Saurabh Arbole Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq']),
    ('Smash PYQ 2026 — Civil Daily IAS', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq']),
    ('Smash PYQ DAW 2026', 'Civil Daily IAS', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_pyq']),
    ('Atish Mathur – GS-2', 'GS-2', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific']),
    ('Bundle: Environment + Economy + Sci-Tech — Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Comprehensive Course on Indian Polity 2027 — Sarmad Mehraj Sir', 'Sarmad Mehraj Sir', 'Both', 'Complete foundation course on Indian Polity (GS Paper 2)', 400.0, ['upsc_subject_specific']),
    ('Economics – Jayant Sir', 'Jayant Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Economy Module — Shivin Sir', 'Shivin Sir', 'Both', 'Prelims + Foundation both', 250.0, ['upsc_subject_specific']),
    ('Economy PCB15 2026 — Mrunal Sir', 'Mrunal Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Economy — Aditya Kaliya Sir', 'Aditya Kaliya Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Environment + Geography — Rajesh Govindraj Sir', 'Rajesh Govindraj Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific']),
    ('Environment 2026 — Sudarshan Gujjar', 'Sudarshan Gujjar', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific']),
    ('Environment – Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific']),
    ('Environment — PMF IAS', 'PMF IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Geography – Thapa Sir', 'Thapa Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Geography — PMF IAS', 'PMF IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Geography — Sudarshan Gujjar', 'Sudarshan Gujjar', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Himanshu Thapa – GS Geography', 'GS Geography', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('History 2026 — Prateek Nayak', 'Prateek Nayak', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('International Relations — Chetan Sir', 'Chetan Sir', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('MCF 4 + MCMA 2026 — Atish Mathur', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific']),
    ('MCPA Prelims Magna Carta 2026 — Atish Mathur', 'Atish Mathur', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Mrunal – PCB 12/13/14', 'Mrunal', 'Both', 'Complete course with handouts, lifetime access', 350.0, ['upsc_subject_specific']),
    ('PMF – Environment', 'Environment', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('PW – Indian Society & Social Justice', 'PW', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('Polity & Governance — Sidharth Arora', 'Sidharth Arora', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('ECONOMICS FOUNDATION', 'Basava Uppin', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific']),
    ('Sci & Tech – Shivin Sir', 'Shivin Sir', 'Both', 'Complete course with handouts, lifetime access', 200.0, ['upsc_subject_specific']),
    ('Sci-Tech + Environment — CP Kaushik Sir', 'CP Kaushik Sir', 'Both', 'ex-Drishti IAS faculty', 350.0, ['upsc_subject_specific']),
    ('Sci-Tech + Environment — Ravi Agrahari Sir', 'Ravi Agrahari Sir', 'Both', 'Complete course with handouts, lifetime access', 400.0, ['upsc_subject_specific']),
    ('Shivin Chaudhary – Environment & S&T', 'Shivin Chaudhary', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_subject_specific']),
    ('Sudarshan Gurjar – Environment & Ecology', 'Environment & Ecology', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_subject_specific']),
    ('MGP Mains 2026 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ts_mains', 'upsc_mains']),
    ('MGP Prime 2027 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 300.0, ['upsc_ts_mains', 'upsc_mains']),
    ('Mains Test Series Bundle 2027', 'Multi-institute Bundle', 'Both', 'Includes test series from: Forum IAS, Vision IAS, Vajiram & Ravi, Drishti IAS, Next IAS, Sarrthi IAS, PW Only IAS, Study IQ & more', 1000.0, ['upsc_ts_mains']),
    ('PTS 2027 — Forum IAS', 'Forum IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ts_prelims']),
    ('PTS 2027 — Vision IAS', 'Vision IAS', 'Both', 'Complete course with handouts, lifetime access', 250.0, ['upsc_ts_prelims']),
    ('Prelims Test Series Bundle 2027', 'Multi-institute Bundle', 'Both', 'Includes test series from: Forum IAS, Vision IAS, Vajiram & Ravi, Drishti IAS, Next IAS, Sarrthi IAS, PW Only IAS, Study IQ & more', 700.0, ['upsc_ts_prelims']),
    ('IFAS – All Subject', 'IFAS', 'Both', 'Complete course with handouts, lifetime access', 1000.0, ['net_jrf_all']),
    ('PW – Paper 1 & History', 'PW', 'Both', 'Complete course with handouts, lifetime access', 800.0, ['net_jrf_all']),
    ('UGC NET JRF December 2026 — Commerce', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_commerce']),
    ('UGC NET JRF June 2027 — Commerce', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_commerce']),
    ('UGC NET JRF December 2026 — Computer Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_computer_science']),
    ('UGC NET JRF June 2027 — Computer Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_computer_science']),
    ('UGC NET JRF December 2026 — Education', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_education']),
    ('UGC NET JRF June 2027 — Education', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_education']),
    ('UGC NET JRF December 2026 — English', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_english']),
    ('UGC NET JRF June 2027 — English', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_english']),
    ('UGC NET JRF December 2026 — Geography', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_geography']),
    ('UGC NET JRF June 2027 — Geography', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_geography']),
    ('UGC NET JRF December 2026 — History', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_history']),
    ('UGC NET JRF June 2027 — History', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_history']),
    ('UGC NET JRF December 2026 — Home Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_home_science']),
    ('UGC NET JRF June 2027 — Home Science', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_home_science']),
    ('UGC NET JRF December 2026 — Law', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_law']),
    ('UGC NET JRF June 2027 — Law', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_law']),
    ('UGC NET JRF December 2026 — Management', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_management']),
    ('UGC NET JRF June 2027 — Management', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_management']),
    ('UGC NET JRF December 2026 — Paper 1', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_paper1']),
    ('UGC NET JRF June 2027 — Paper 1', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_paper1']),
    ('UGC NET JRF December 2026 — Philosophy', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_philosophy']),
    ('UGC NET JRF June 2027 — Philosophy', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_philosophy']),
    ('UGC NET JRF December 2026 — Polity', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_polity']),
    ('UGC NET JRF June 2027 — Polity', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_polity']),
    ('UGC NET JRF December 2026 — Psychology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_psychology']),
    ('UGC NET JRF June 2027 — Psychology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_psychology']),
    ('UGC NET JRF December 2026 — Public Administration', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_public_administration']),
    ('UGC NET JRF June 2027 — Public Administration', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_public_administration']),
    ('UGC NET JRF December 2026 — Sociology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 800.0, ['net_jrf_sociology']),
    ('UGC NET JRF June 2027 — Sociology', 'ADDA24*7 / JRF Adda', 'Both', 'Full syllabus update, lifetime access to that session', 1000.0, ['net_jrf_sociology']),
]
