"""Full course catalog seed data — see database.py seed_courses(). Regenerate
from the master xlsx if the catalog changes; this file is intentionally just
data, no logic."""

# Auto-generated seed data from the UPSC Course Master List (priced courses +
# institute/faculty catalog), organized by section. Price=None means "Coming Soon".
COURSE_SEED = [
    # (name, faculty, medium, notes, price_or_None, [section_keys])
    ("MMP+ 2027 (Sarrthi IAS)", "", "", "", 350.0, ["upsc_mains"]),
    ("MMP+ 2026 (Sarrthi IAS)", "", "", "", 300.0, ["upsc_mains"]),
    ("Decode Mains 2026/27 (Mudit Jain) — Combo without CA", "", "", "", 400.0, ["upsc_mains"]),
    ("Mains Excellence Plus — Combo with CA", "", "", "", 500.0, ["upsc_mains"]),
    ("Sankalp Mains 2027", "", "", "", 500.0, ["upsc_mains"]),
    ("Think IAS by Prakash Chitkara (Mains Module)", "", "", "", 500.0, ["upsc_mains"]),
    ("Write Smart (Shivin Chaudhary)", "", "", "", 150.0, ["upsc_mains"]),
    ("Forum IAS MGP 2027", "", "", "", 300.0, ["upsc_mains"]),
    ("Nitya Pargati 2027 Batch 3", "", "", "", 300.0, ["upsc_mains"]),
    ("AWFG 2026", "", "", "", 400.0, ["upsc_mains"]),
    ("Mains Edge Vision IAS 2026", "", "", "", 400.0, ["upsc_mains"]),
    ("MK Yadav QEP & TEP 2026/27", "", "", "", 450.0, ["upsc_mains"]),
    ("LevelUP MMP 2026", "", "", "", 1500.0, ["upsc_mains"]),
    ("PSIR OGP 2026", "", "", "", 400.0, ["upsc_mains"]),
    ("GS Foundation Batch (1/3/4/5/6 — any one)", "", "", "", 600.0, ["upsc_foundation"]),
    ("MagnaCarta Foundation 5 (2027)", "", "", "", 300.0, ["upsc_foundation"]),
    ("Essay (Mudit Jain) 2027", "", "", "", 250.0, ["upsc_essay"]),
    ("Mudit Jain Yearlong CA 2027", "", "", "", 300.0, ["upsc_ca"]),
    ("Satvik Bhan CA 2027", "", "", "", 250.0, ["upsc_ca"]),
    ("Dipin Sir CA-VA (Mains & Prelims)", "", "", "", 350.0, ["upsc_ca"]),
    ("Ethics (Mudit Jain) 2027", "", "", "", 250.0, ["upsc_ethics"]),
    ("Ethics Marks Booster 2026", "", "", "", 200.0, ["upsc_ethics"]),
    ("Ethics by Piyush Sir 2027", "", "", "", 350.0, ["upsc_ethics"]),
    ("Ethics Samagra (Hindi Medium) — Piyush Sir", "", "", "", 400.0, ["upsc_ethics"]),
    ("Amit Garg CSAT 2027", "", "", "", 300.0, ["upsc_csat"]),
    ("Sarrthi IAS CSAT 2027", "", "", "", 300.0, ["upsc_csat"]),
    ("Smash PYQ DAW 2026", "", "", "", 400.0, ["upsc_pyq"]),
    ("Prelims Test Series Bundle 2027", "", "", "", 700.0, ["upsc_ts_prelims"]),
    ("Mains Test Series Bundle 2027", "", "", "", 1000.0, ["upsc_ts_mains"]),
    ("Sociology — Sleepy Classes Batch 4 2026", "", "", "", 500.0, ["optional_sociology"]),
    ("Anthropology — Karandeep Sir 2026", "", "", "", 600.0, ["optional_anthropology"]),
    ("PSIR — OGP 2026", "", "", "", 400.0, ["optional_psir"]),
    ("Philosophy — Sarrthi IAS 2027", "", "", "", 500.0, ["optional_philosophy"]),
    ("Sarrthi IAS Optional 2027 (Sociology/Anthropology/PSIR)", "", "", "", 500.0, ["optional_sociology", "optional_anthropology", "optional_psir"]),
    ("UPPSC Samagra Batch (Forum IAS)", "", "", "", 400.0, ["uppsc"]),
    ("Any 2 courses", "", "", "", 600.0, ["combo_deals"]),
    ("Any 3 courses", "", "", "", 800.0, ["combo_deals"]),
    ("Any 4 courses", "", "", "", 1000.0, ["combo_deals"]),
    ("Any 5 courses", "", "", "", 1200.0, ["combo_deals"]),
    ("Vision IAS — GS 2026, all batches", "", "", "English + Hindi both", None, ["upsc_foundation"]),
    ("Vajiram & Ravi — GS 2026", "", "", "", None, ["upsc_foundation"]),
    ("Next IAS — GS 2026", "", "", "", None, ["upsc_foundation"]),
    ("PW (Only IAS) — GS Foundation 2026", "", "", "English + Hindi", None, ["upsc_foundation"]),
    ("Sarrthi IAS — GS 2026 + 2027 both", "", "", "", None, ["upsc_foundation"]),
    ("KGS — All batches", "", "", "English + Hindi + Hinglish", None, ["upsc_foundation"]),
    ("Forum IAS — GS 2027", "", "", "", None, ["upsc_foundation"]),
    ("Vision IAS — NCERT Course 2026", "", "", "Best starting point for freshers", None, ["upsc_foundation"]),
    ("Unacademy — GS Module + Foundation", "", "", "", None, ["upsc_foundation"]),
    ("Economy PCB15 2026 — Mrunal Sir", "Mrunal Sir", "", "", None, ["upsc_subject_specific"]),
    ("Economy Module — Shivin Sir", "Shivin Sir", "", "Prelims + Foundation both", None, ["upsc_subject_specific"]),
    ("Prelims Revision — Basava Uppin", "Basava Uppin", "", "Prelims + Foundation both", None, ["upsc_subject_specific"]),
    ("Economy — Hope Tushant", "Hope Tushant", "", "", None, ["upsc_subject_specific"]),
    ("Economy 2026 — Jayant Parikshit", "Jayant Parikshit", "", "", None, ["upsc_subject_specific"]),
    ("Economy GS — Vajiram & Ravi", "Vajiram & Ravi", "", "", None, ["upsc_subject_specific"]),
    ("Economy — Aditya Kaliya Sir", "Aditya Kaliya Sir", "", "", None, ["upsc_subject_specific"]),
    ("Bundle: Environment + Economy + Sci-Tech — Shivin Sir", "Shivin Sir", "", "", None, ["upsc_subject_specific"]),
    ("Environment — PMF IAS", "PMF IAS", "", "", None, ["upsc_subject_specific"]),
    ("Environment 2026 — Sudarshan Gujjar", "Sudarshan Gujjar", "", "", None, ["upsc_subject_specific"]),
    ("Sci-Tech + Environment — CP Kaushik Sir", "CP Kaushik Sir", "", "ex-Drishti IAS faculty", None, ["upsc_subject_specific"]),
    ("Sci-Tech + Environment — Ravi Agrahari Sir", "Ravi Agrahari Sir", "", "", None, ["upsc_subject_specific"]),
    ("Environment + Geography — Rajesh Govindraj Sir", "Rajesh Govindraj Sir", "", "", None, ["upsc_subject_specific"]),
    ("Geography — Sudarshan Gujjar", "Sudarshan Gujjar", "", "", None, ["upsc_subject_specific"]),
    ("Geography — PMF IAS", "PMF IAS", "", "", None, ["upsc_subject_specific"]),
    ("MCPA Prelims Magna Carta 2026 — Atish Mathur", "Atish Mathur", "", "", None, ["upsc_subject_specific"]),
    ("MCF 4 + MCMA 2026 — Atish Mathur", "Atish Mathur", "", "", None, ["upsc_subject_specific"]),
    ("International Relations — Chetan Sir", "Chetan Sir", "", "", None, ["upsc_subject_specific"]),
    ("Polity & Governance — Sidharth Arora", "Sidharth Arora", "", "", None, ["upsc_subject_specific"]),
    ("History 2026 — Prateek Nayak", "Prateek Nayak", "", "", None, ["upsc_subject_specific"]),
    ("CSAT 2027 — Amit Garg", "Amit Garg", "", "", None, ["upsc_csat"]),
    ("CSAT — Vision IAS", "Vision IAS", "", "", None, ["upsc_csat"]),
    ("UNGIST x Sarrthi 2026 — Ram Mohan Pandey Sir", "Ram Mohan Pandey Sir", "", "", None, ["upsc_csat"]),
    ("CSAT by IITians 2027 — Sunya IAS", "Sunya IAS", "", "", None, ["upsc_csat"]),
    ("CSAT Hindi 2026 — Madhukar Kotwe", "Madhukar Kotwe", "", "", None, ["upsc_csat"]),
    ("PW Only IAS 2027 — Rishabh Sharma", "Rishabh Sharma", "", "", None, ["upsc_csat"]),
    ("CSAT 2026 — Hope Tushant", "Hope Tushant", "", "", None, ["upsc_csat"]),
    ("CSAT 2026 — Sudarshan Lodha", "Sudarshan Lodha", "", "", None, ["upsc_csat"]),
    ("Smart PYQ Course 2026 — Vision IAS", "Vision IAS", "", "", None, ["upsc_pyq"]),
    ("Logical Elimination 2026 — Civil Daily IAS", "Civil Daily IAS", "", "", None, ["upsc_pyq"]),
    ("Smash PYQ 2026 — Civil Daily IAS", "Civil Daily IAS", "", "", None, ["upsc_pyq"]),
    ("Eklavya PYQ 2026 — Sunya IAS", "Sunya IAS", "", "", None, ["upsc_pyq"]),
    ("PYQ Dominator 2026 — Vajiram & Ravi", "Vajiram & Ravi", "", "", None, ["upsc_pyq"]),
    ("PYQ 2026 — Forum IAS", "Forum IAS", "", "", None, ["upsc_pyq"]),
    ("PYQ 2025 — Arjuna IAS", "Arjuna IAS", "", "", None, ["upsc_pyq"]),
    ("PYQ Edge, UPSC Compass 2026 — Saurabh Arbole Sir", "Saurabh Arbole Sir", "", "", None, ["upsc_pyq"]),
    ("PTS 2027 — Forum IAS", "Forum IAS", "", "", None, ["upsc_ts_prelims"]),
    ("PTS 2027 — Vision IAS", "Vision IAS", "", "", None, ["upsc_ts_prelims"]),
    ("MMP+ 2026 & 2027 both — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["upsc_mains"]),
    ("Mains Edge, 45 Days 2026 — Vision IAS", "Vision IAS", "", "", None, ["upsc_mains"]),
    ("MMP 2026 — Levelup IAS", "Levelup IAS", "", "", None, ["upsc_mains"]),
    ("GS Advance 2026 — Forum IAS", "Forum IAS", "", "", None, ["upsc_mains"]),
    ("Sankalp Mains — Sudarshan Lodha", "Sudarshan Lodha", "", "", None, ["upsc_mains"]),
    ("Write Smart + GS-3 Module — Shivin Sir", "Shivin Sir", "", "", None, ["upsc_mains"]),
    ("Mains QEP 8 — Mrunal Sir", "Mrunal Sir", "", "", None, ["upsc_mains"]),
    ("Decode Mains 2027 — Mudit Jain", "Mudit Jain", "", "", None, ["upsc_mains"]),
    ("MEP 2027 — Mudit Jain", "Mudit Jain", "", "", None, ["upsc_mains"]),
    ("GS Advance Mains 2026 — Vision IAS", "Vision IAS", "", "", None, ["upsc_mains"]),
    ("Smash Mains 2026", "", "", "", None, ["upsc_mains"]),
    ("Vision IAS 2026 (Mains) — Smriti Ma'am", "Smriti Ma'am", "", "", None, ["upsc_mains"]),
    ("Educamy 2026 — Shabbir Sir", "Shabbir Sir", "", "", None, ["upsc_mains"]),
    ("Vajiram & Ravi 2026 (Mains) — Piyush Sir", "Piyush Sir", "", "", None, ["upsc_mains"]),
    ("2026 / 2027 — Animesh Sir", "Animesh Sir", "", "", None, ["upsc_mains"]),
    ("Triumph IAS 2025 — Vikas Ranjan", "Vikas Ranjan", "", "", None, ["upsc_mains"]),
    ("Muditjain 2026 & 2027 — Mudit Jain Sir", "Mudit Jain Sir", "", "", None, ["upsc_mains"]),
    ("CA Mains 2026 — Forum IAS", "Forum IAS", "", "", None, ["upsc_ca"]),
    ("Mains 365 2026 — Vision IAS", "Vision IAS", "", "", None, ["upsc_ca"]),
    ("CA Mains 2026 + 2027 Live — Satvik Bhan", "Satvik Bhan", "", "", None, ["upsc_ca"]),
    ("Monthly CA for Mains 2026 — Vision IAS", "Vision IAS", "", "", None, ["upsc_ca"]),
    ("Current Affairs 2026 + 2027 both — Mudit Jain", "Mudit Jain", "", "", None, ["upsc_ca"]),
    ("Yearly CA 2027 — Sunya IAS", "Sunya IAS", "", "", None, ["upsc_ca"]),
    ("CA VA Mains 2026 + CA VA Live 2027 both — Dipin Sir", "Dipin Sir", "", "", None, ["upsc_ca"]),
    ("MGP Prime 2027 — Forum IAS", "Forum IAS", "", "", None, ["upsc_ts_mains"]),
    ("MGP Mains 2026 — Forum IAS", "Forum IAS", "", "", None, ["upsc_ts_mains"]),
    ("Sociology QEP+ 2026", "", "", "", None, ["optional_sociology"]),
    ("Anthropology QEP+ 2026", "", "", "", None, ["optional_anthropology"]),
    ("History QEP+ 2026", "", "", "", None, ["optional_history"]),
    ("Philosophy QEP+ 2026", "", "", "", None, ["optional_philosophy"]),
    ("PSIR QEP+ 2026", "", "", "", None, ["optional_psir"]),
    ("Geography QEP+ 2026", "", "", "", None, ["optional_geography"]),
    ("Sunya IAS • Hornbill • Vajiram & Ravi", "", "", "", None, ["optional_forestry"]),
    ("Planet • Vajiram & Ravi • Evolution", "", "", "", None, ["optional_geology"]),
    ("Mitra IAS • Tanu Jain • Study IQ • PW • KGS", "", "", "", None, ["optional_philosophy"]),
    ("Raus x Anantam IAS • Study IQ", "", "", "", None, ["optional_psychology"]),
    ("Philosophy QEP Mains 2026/2027 — Sarrthi IAS", "Sarrthi IAS", "Crash", "", None, ["optional_philosophy"]),
    ("Ranker Classes • Study IQ • PW Only IAS", "", "", "", None, ["optional_commerce_and_accountancy"]),
    ("Vikas Divyakirti Sir • PW Only IAS • Study IQ • KGS", "", "", "", None, ["optional_hindi_literature"]),
    ("Lukmaan IAS — Ansari Sir", "Ansari Sir", "", "", None, ["optional_public_administration"]),
    ("Sarrthi IAS — Ashutosh Pandey", "Ashutosh Pandey", "", "", None, ["optional_public_administration"]),
    ("Vision IAS — Pawan Sir", "Pawan Sir", "", "", None, ["optional_public_administration"]),
    ("PW / Study IQ / KGS — 2026 batches", "2026 batches", "", "", None, ["optional_public_administration"]),
    ("Study IQ — 2026", "2026", "", "", None, ["optional_public_administration"]),
    ("Sarrthi IAS — Pub Ad QEP", "Pub Ad QEP", "", "", None, ["optional_public_administration"]),
    ("Karandeep Sir — Levelup IAS", "Levelup IAS", "", "", None, ["optional_anthropology"]),
    ("2026 | 2025 both — Next IAS", "Next IAS", "", "", None, ["optional_anthropology"]),
    ("CP Kaushik Sir 2027 (ex-Drishti faculty)", "", "", "", None, ["optional_anthropology"]),
    ("2026 — Vision IAS", "Vision IAS", "", "", None, ["optional_anthropology"]),
    ("Shiva Teja 2026 — Ace With Ease", "Ace With Ease", "", "", None, ["optional_anthropology"]),
    ("Harpreet Kukreja 2026 — PW", "PW", "", "", None, ["optional_anthropology"]),
    ("Natraj Sir 2026 — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_anthropology"]),
    ("Hima Bindu 2025", "", "", "", None, ["optional_anthropology"]),
    ("2026 — Study IQ", "Study IQ", "", "", None, ["optional_anthropology"]),
    ("2026 — KGS", "KGS", "", "", None, ["optional_anthropology"]),
    ("2025 — Sapiens IAS", "Sapiens IAS", "", "", None, ["optional_anthropology"]),
    ("Sosin Ma'am 2024 — Sunya IAS", "Sunya IAS", "", "", None, ["optional_anthropology"]),
    ("Anthropology Advance 2025 — Next IAS", "Next IAS", "", "", None, ["optional_anthropology"]),
    ("DAMP 2026 / Crash Course 2025 — Levelup IAS", "Levelup IAS", "", "", None, ["optional_anthropology"]),
    ("Natraj Sir — Anthropology QEP 2026 — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_anthropology"]),
    ("Shiva Teja — Anthropology Advance 555 — Ace With Ease", "Ace With Ease", "", "", None, ["optional_anthropology"]),
    ("Sumit Rewri 2027 — PW", "PW", "", "", None, ["optional_anthropology"]),
    ("Piyush Chaubey Sir 2026|2025 — Next IAS", "Next IAS", "", "", None, ["optional_psir"]),
    ("Bhartendu Sir 2026 — PW", "PW", "", "", None, ["optional_psir"]),
    ("Rahul Puri 2026 — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_psir"]),
    ("Shashank Tyagi — Study IQ", "Study IQ", "", "", None, ["optional_psir"]),
    ("2026 / 2024 — Vision IAS / Vajiram & Ravi", "Vision IAS / Vajiram & Ravi", "", "", None, ["optional_psir"]),
    ("PSIR QEP — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_psir"]),
    ("PSIR Crash Course 2026 — Study IQ", "Study IQ", "", "", None, ["optional_psir"]),
    ("Shubhra Ranjan — PSIR Crash Course 2025|2026", "", "", "", None, ["optional_psir"]),
    ("Pranay Agrawal 2025|2026|2027 all — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_sociology"]),
    ("Raj Sir 2026 — Next IAS", "Next IAS", "", "", None, ["optional_sociology"]),
    ("Smriti Ma'am 2026 — Vision IAS", "Vision IAS", "", "", None, ["optional_sociology"]),
    ("Ravi Shekhar Sir 2026 — PW", "PW", "", "", None, ["optional_sociology"]),
    ("Diwakar Bothra 2026|2027 both — Study IQ", "Study IQ", "", "", None, ["optional_sociology"]),
    ("2026 — Sleepy Classes", "Sleepy Classes", "", "", None, ["optional_sociology"]),
    ("Vikas Ranjan 2026", "", "", "", None, ["optional_sociology"]),
    ("Mohapatra Sir 2023 — Vajiram & Ravi", "Vajiram & Ravi", "", "", None, ["optional_sociology"]),
    ("2024 — Sunya IAS", "Sunya IAS", "", "", None, ["optional_sociology"]),
    ("Nishant Sir 2023", "", "", "", None, ["optional_sociology"]),
    ("2026 + S Pandey 2025 — PW / Study IQ / KGS", "PW / Study IQ / KGS", "", "", None, ["optional_sociology"]),
    ("Nishant Sir — Sociology Crash Course 2025", "", "", "", None, ["optional_sociology"]),
    ("Crash Course + Answer Writing Program — Study IQ", "Study IQ", "", "", None, ["optional_sociology"]),
    ("Pranay Agrawal Sir — Sociology QEP 2026 — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_sociology"]),
    ("Sociology Crash Course 2025 — Understand UPSC", "Understand UPSC", "", "", None, ["optional_sociology"]),
    ("History Optional 2026 — Levelup IAS", "Levelup IAS", "", "", None, ["optional_history"]),
    ("Vikas Ahlawat Sir 2026 — PW", "PW", "", "", None, ["optional_history"]),
    ("Awadh Ojha Sir (English)", "", "", "", None, ["optional_history"]),
    ("HOT 500 2025|2026 both — Levelup IAS", "Levelup IAS", "", "", None, ["optional_history"]),
    ("History Optional Crash Course — Study IQ", "Study IQ", "", "", None, ["optional_history"]),
    ("History QEP cum Crash Course — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_history"]),
    ("Himanshu Sir — Guidance IAS x Sarrthi", "Guidance IAS x Sarrthi", "", "", None, ["optional_geography"]),
    ("Shabbir Sir — Educamy", "Educamy", "", "", None, ["optional_geography"]),
    ("Himanshu Thapa — PW", "PW", "", "", None, ["optional_geography"]),
    ("Himanshu Sir — Geography 500+", "", "", "", None, ["optional_geography"]),
    ("Crash Course — Study IQ", "Study IQ", "", "", None, ["optional_geography"]),
    ("Shabbir Sir — Geo MSP 2026", "", "", "", None, ["optional_geography"]),
    ("Geography QEP+ 2026 — Sarrthi IAS", "Sarrthi IAS", "", "", None, ["optional_geography"]),
    ("Next IAS • PW • Mathocrate • Study IQ • KGS", "", "Main", "", None, ["optional_mathematics"]),
    ("Mathocrate — Math Optional • PW — Math Crash Course", "", "Crash", "", None, ["optional_mathematics"]),
    ("Vibhash Jha 2026 — Next IAS", "Next IAS", "", "", None, ["optional_economics"]),
    ("Bliss Point 2026", "", "", "", None, ["optional_economics"]),
    ("De Facto — 2026 — Study IQ", "Study IQ", "", "", None, ["optional_economics"]),
    ("Sarrthi IAS 2027 B3", "", "", "GS Foundation 2027 — LIVE, Daily Update", None, ["upsc_subject_specific"]),
    ("Mudit Jain Current Affairs 2027", "", "", "LIVE Classes, Regular Update", None, ["upsc_ca"]),
    ("MMP+ 2027", "", "", "LIVE Classes, Regular Update", None, ["upsc_subject_specific"]),
    ("Write Smart 2027", "", "", "LIVE Classes, Regular Update", None, ["upsc_subject_specific"]),
    ("Mudit Jain Ethics 2027", "", "", "Complete Classes, Regular Update", None, ["upsc_ethics"]),
    ("PCB 15/16 – Mrunal Sir (Economics)", "", "", "", None, ["optional_economics"]),
    ("Anthropology – Karandeep Sir", "", "", "", None, ["optional_anthropology"]),
    ("Vision IAS – Sociology 2026", "", "", "", None, ["optional_sociology"]),
    ("Sankalp Prelims 2026 – Sudarshan Lodha", "", "", "", None, ["upsc_subject_specific"]),
    ("Saarthi IAS – MAISE", "", "", "", None, ["upsc_subject_specific"]),
    ("Vision IAS – PT365", "", "", "", None, ["upsc_subject_specific"]),
    ("CSAT – Sunya IAS", "", "", "", None, ["upsc_csat"]),
    ("Shivin Chaudhary – Environment & S&T", "", "", "", None, ["upsc_subject_specific"]),
    ("Shivin Chaudhary – Economics", "", "", "", None, ["optional_economics"]),
    ("Psychology Optional – StudyIQ PRO", "", "", "", None, ["optional_psychology"]),
    ("Mudit Jain – Current Affairs 2027 (listed as 20267 in source, likely typo)", "", "", "", None, ["upsc_ca"]),
    ("Saarthi IAS – Prelims Navigator 2026", "", "", "", None, ["upsc_subject_specific"]),
    ("MBA CAT Pro – 2025", "", "", "", None, ["other_misc"]),
    ("Rishi Jain – Economics (Hindi)", "", "", "", None, ["optional_economics"]),
    ("Atish Mathur – GS-2", "", "", "", None, ["upsc_subject_specific"]),
    ("Himanshu Thapa – GS Geography", "", "", "", None, ["upsc_subject_specific"]),
    ("Careerwill – CSAT", "", "", "", None, ["upsc_csat"]),
    ("Shubhra Ranjan – Essay 2026", "", "", "", None, ["upsc_essay"]),
    ("Vision IAS – Foundation (With Notes)", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Vajiram & Ravi – Foundation", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Unacademy – GS Foundation", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Saarthi IAS – GS Foundation", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Physics Wallah – GS Foundation (Hindi + English)", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Next IAS – Foundation", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Eduteria BPSC Tejas Batch", "", "English Medium", "", None, ["upsc_foundation"]),
    ("Drishti IAS – Foundation (Without Notes)", "", "Hindi Medium", "", None, ["upsc_foundation"]),
    ("PW – Sankalp Hindi", "", "Hindi Medium", "", None, ["upsc_foundation"]),
    ("Khan Sir – UPSC Foundation", "", "Hindi Medium", "", None, ["upsc_foundation"]),
    ("Sanskriti IAS – Foundation", "", "Hindi Medium", "", None, ["upsc_foundation"]),
    ("Vision IAS – Hindi Foundation", "", "Hindi Medium", "", None, ["upsc_foundation"]),
    ("Buniyaad – PW", "", "", "", None, ["upsc_foundation"]),
    ("OJANK IAS – NCERT Course", "", "", "", None, ["upsc_foundation"]),
    ("Shubhra Ranjan – NCERT Programme", "", "", "", None, ["upsc_foundation"]),
    ("Vikas Divyakirti – Ethics (English + Hindi both)", "", "", "", None, ["upsc_ethics"]),
    ("Lukmaan IAS – Ansari Sir", "", "", "", None, ["upsc_ethics"]),
    ("Mudit Jain – Ethics Module", "", "", "", None, ["upsc_ethics"]),
    ("PW – Indian Society & Social Justice", "", "", "", None, ["upsc_subject_specific"]),
    ("Governance – Full Course + Notes", "", "", "", None, ["upsc_subject_specific"]),
    ("Geography – Thapa Sir", "", "", "", None, ["upsc_subject_specific"]),
    ("Sudarshan Gurjar – Environment & Ecology", "", "", "", None, ["upsc_subject_specific"]),
    ("Bookstawa – Economics", "", "", "", None, ["upsc_subject_specific"]),
    ("Mrunal – PCB 12/13/14", "", "", "", None, ["upsc_subject_specific"]),
    ("Rishi Jain – Economics Hindi", "", "", "", None, ["upsc_subject_specific"]),
    ("Economics – Jayant Sir", "", "", "", None, ["upsc_subject_specific"]),
    ("Environment – Shivin Sir", "", "", "", None, ["upsc_subject_specific"]),
    ("Sci & Tech – Shivin Sir", "", "", "", None, ["upsc_subject_specific"]),
    ("PMF – Environment", "", "", "", None, ["upsc_subject_specific"]),
    ("PMF – Geography", "", "", "", None, ["upsc_subject_specific"]),
    ("PMF – History", "", "", "", None, ["upsc_subject_specific"]),
    ("Mudit Jain – Current Affairs 2027", "", "", "", None, ["upsc_ca"]),
    ("Saarthi IAS – Prelims Navigator", "", "", "", None, ["upsc_ca"]),
    ("PW – Rishab Sir", "", "", "", None, ["upsc_csat"]),
    ("Ram Mohan Pandey – Sarrthi IAS", "", "", "", None, ["upsc_csat"]),
    ("Vision IAS – English (With Notes)", "", "", "", None, ["upsc_csat"]),
    ("Vision IAS – Hindi (Without Notes)", "", "", "", None, ["upsc_csat"]),
    ("CSAT – Sarrthi IAS", "", "", "", None, ["upsc_csat"]),
    ("Amit Garg – CSAT", "", "", "", None, ["upsc_csat"]),
    ("Sunya IAS – CSAT", "", "", "", None, ["upsc_csat"]),
    ("Write Smart – Shivin Sir 2027", "", "", "", None, ["upsc_mains"]),
    ("M.K. Yadav – QEP 2026", "", "", "", None, ["upsc_mains"]),
    ("Shabbir Sir – Essay", "", "", "", None, ["upsc_mains"]),
    ("Rao IAS – QIP", "", "", "", None, ["upsc_mains"]),
    ("Saarthi IAS – MMP+ 2025", "", "", "", None, ["upsc_pyq"]),
    ("Forum IAS – Prelims PYQ Analysis", "", "", "", None, ["upsc_pyq"]),
    ("Forum IAS – UPPSC 2025", "", "", "", None, ["upsc_pyq"]),
    ("Smash Mains 2026 – CivilsDaily", "", "", "", None, ["upsc_pyq"]),
    ("Vision PYQ Course – Prelims", "", "", "", None, ["upsc_pyq"]),
    ("OJANK IAS – NCERT Advanced", "", "", "", None, ["upsc_mains"]),
    ("Vision IAS – Advanced GS 2025", "", "", "", None, ["upsc_mains"]),
    ("Neetu Mam – Latest Batch", "", "", "", None, ["other_misc"]),
    ("PW – Himanshu Thapa", "", "", "", None, ["optional_geography"]),
    ("StudyIQ – Geography Optional", "", "", "", None, ["optional_geography"]),
    ("Pranay Agrawal 2026 – Sarrthi IAS", "", "", "", None, ["optional_sociology"]),
    ("PW – Ravi Shekhar Sir", "", "", "", None, ["optional_sociology"]),
    ("PW – Sociology (Hindi)", "", "", "", None, ["optional_sociology"]),
    ("PW – Sociology (Offline)", "", "", "", None, ["optional_sociology"]),
    ("StudyIQ – Sociology", "", "", "", None, ["optional_sociology"]),
    ("Sleepy Classes – Sociology", "", "", "", None, ["optional_sociology"]),
    ("IAS Gurukul – Sociology", "", "", "", None, ["optional_sociology"]),
    ("Level Up – Sociology", "", "", "", None, ["optional_sociology"]),
    ("Vikas Ranjan – Sociology", "", "", "", None, ["optional_sociology"]),
    ("Triumph IAS – Sociology", "", "", "", None, ["optional_sociology"]),
    ("StudyIQ – Sainil Nagare", "", "", "", None, ["optional_history"]),
    ("PW – Ahlawat Sir", "", "", "", None, ["optional_history"]),
    ("History Optional – PYQ Course", "", "", "", None, ["optional_history"]),
    ("Sanskriti IAS – Hindi", "", "", "", None, ["optional_history"]),
    ("KGS", "", "", "", None, ["optional_history"]),
    ("Kirthika Mam – Unacademy", "", "", "", None, ["optional_history"]),
    ("PW – Anthropology Offline 2026", "", "", "", None, ["optional_anthropology"]),
    ("PW – Anthropology Optional", "", "", "", None, ["optional_anthropology"]),
    ("Next IAS – Anthropology", "", "", "", None, ["optional_anthropology"]),
    ("PW – Maths Optional", "", "", "", None, ["optional_mathematics"]),
    ("KGS – Bilingual Maths Optional", "", "", "", None, ["optional_mathematics"]),
    ("KGS – Mathematics Optional (Bilingual, NEW)", "", "", "", None, ["optional_mathematics"]),
    ("Sunya IAS – Agriculture", "", "", "", None, ["optional_agriculture"]),
    ("StudyIQ – Agriculture", "", "", "", None, ["optional_agriculture"]),
    ("Vajiram & Ravi – PSIR Optional", "", "English", "", None, ["optional_psir"]),
    ("PW – Eng Bharat Sir", "", "English", "", None, ["optional_psir"]),
    ("Next IAS 2025", "", "English", "", None, ["optional_psir"]),
    ("Study IQ", "", "English", "", None, ["optional_psir", "optional_public_administration"]),
    ("PW – Adarsh Sir", "", "Hindi", "", None, ["optional_psir"]),
    ("Rajesh Mishra", "", "Hindi", "", None, ["optional_psir"]),
    ("Lukmaan IAS", "", "", "", None, ["optional_public_administration"]),
    ("PW", "", "", "", None, ["optional_public_administration"]),
    ("Tanu Jain – Tathastu ICS (Latest 2025)", "", "", "", None, ["optional_philosophy"]),
    ("StudyIQ PRO", "", "", "", None, ["optional_psychology"]),
    ("StudyIQ PRO (NEW)", "", "", "", None, ["optional_economics"]),
    ("UPPSC Sarv Saksham Foundation 2026", "", "", "", None, ["uppsc"]),
    ("Study IQ 2026", "", "", "", None, ["uppsc"]),
    ("RWA 2026 (Hindi Medium)", "", "", "", None, ["uppsc"]),
    ("Sanskriti IAS (Old)", "", "", "", None, ["uppsc"]),
    ("UPPSC – RTQs Batch", "", "", "", None, ["uppsc"]),
    ("UPPCS – Test Series (Video Solutions)", "", "", "", None, ["uppsc"]),
    ("KGS – Complete BPSC Foundation (Bilingual/Hinglish, NEW)", "", "", "", None, ["bpsc"]),
    ("Eduteria Tejas Foundation 2026", "", "", "", None, ["bpsc"]),
    ("Eduteria Prelims Batch – Hindi", "", "", "", None, ["bpsc"]),
    ("Eduteria Prelims Batch – English", "", "", "", None, ["bpsc"]),
    ("Study IQ Smart Course (VOD)", "", "", "", None, ["ukpsc"]),
    ("StudyIQ UPSC + UKPSC", "", "", "", None, ["ukpsc"]),
    ("PW – Paper 1 & History", "", "", "", None, ["net_jrf_all"]),
    ("IFAS – All Subject", "", "", "", None, ["net_jrf_all"]),
    ("JRF Adda – All Subjects", "", "", "", None, ["net_jrf_all"]),
    ("MBA Pro 2026", "", "", "", None, ["other_misc"]),
    ("MBA Elite 2026", "", "", "", None, ["other_misc"]),
    ("PW MBA Ignite 2025", "", "", "", None, ["other_misc"]),
    ("MBA Elite 2025 (Weekend)", "", "", "", None, ["other_misc"]),
    ("MBA Pro 2026 (CAT + OMETs)", "", "", "", None, ["other_misc"]),
    ("Samarth 2.0 2026: General MBA", "", "", "", None, ["other_misc"]),
    ("MBA Elite 2025", "", "", "", None, ["other_misc"]),
    ("PW MBA CAT Pro 2025", "", "", "", None, ["other_misc"]),
    ("CUET PG MBA", "", "", "", None, ["other_misc"]),
]